const retailKeywords = [
  "support",
  "resistance",
  "fakeout",
  "fakeouts",
  "fake out",
  "fake outs",
  "fake-out",
  "fake-outs",
  "bull-flag",
  "bull flag",
  "bear-flag",
  "bear flag",
  "head and shoulders",
  "macd",
  "rsi",
  "ema",
  "double bottom",
  "triple bottom",
  "double top",
  "triple top",
  "rising wedge",
  "falling wedge",
  "bullish pennant",
  "bearish pennant",
  "bullish rectangle",
  "bearish rectangle",
  "ascending triangle",
  "descending triangle",
  "symmetrical triangle",
  "trendlines",
  "trendline",
  "trend line",
  "trend lines",
  "stop hunt",
  "stophunt",
  "moving average",
];

export default retailKeywords;
